name: Deploy PR to VPS

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t segimed/frontend:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push segimed/frontend:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            bash /home/deploy_pr.sh $SHORT_SHA segimed/frontend:${{ github.sha }}

      - name: Comment PR
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\": \"http://pr-${SHORT_SHA}.test.segimed.com/ ! 👋\"}" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
